services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    image: finance-superset:latest
    container_name: finance-superset

    ports:
      - "8088:8088"

    environment:
      SUPERSET_SECRET_KEY: "finance_dwh_local_secret_key_change_later"

    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin
      --username admin
      --firstname Admin
      --lastname User
      --email admin@example.com
      --password admin || true &&
      superset init &&
      gunicorn
      --bind 0.0.0.0:8088
      --workers 2
      --timeout 120
      'superset.app:create_app()'
      "

    restart: unless-stopped

    networks:
      - finance_dwh_default

networks:
  finance_dwh_default:
    external: true
