version: 2

models:
  - name: lu_company
    description: "Company lookup table"

    columns:
      - name: ticker_key
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

      - name: ticker
        description: "Ticker name for each company"
        data_tests:
          - unique
          - not_null

      - name: price_date
        data_tests:
          - not null

      - name: close_price
        data_tests:
          - not null
